package com.wu.vms.mapper;

import com.wu.vms.dataobject.MenuDO;

import java.util.List;

public interface MenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    int insert(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    int insertSelective(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    MenuDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    int updateByPrimaryKeySelective(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    int updateByPrimaryKey(MenuDO record);

    List<MenuDO> getMenuByUserId(Integer userId);
}