package com.wu.vms.dataobject;

public class MenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.component
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_roleId
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private Integer menuRoleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.iconCls
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private String iconcls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.keepAlive
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private Boolean keepalive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parentId
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.path
     *
     * @return the value of menu.path
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.path
     *
     * @param path the value for menu.path
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.component
     *
     * @return the value of menu.component
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.component
     *
     * @param component the value for menu.component
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_roleId
     *
     * @return the value of menu.menu_roleId
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public Integer getMenuRoleid() {
        return menuRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_roleId
     *
     * @param menuRoleid the value for menu.menu_roleId
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setMenuRoleid(Integer menuRoleid) {
        this.menuRoleid = menuRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.iconCls
     *
     * @return the value of menu.iconCls
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.iconCls
     *
     * @param iconcls the value for menu.iconCls
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls == null ? null : iconcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.keepAlive
     *
     * @return the value of menu.keepAlive
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public Boolean getKeepalive() {
        return keepalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.keepAlive
     *
     * @param keepalive the value for menu.keepAlive
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setKeepalive(Boolean keepalive) {
        this.keepalive = keepalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parentId
     *
     * @return the value of menu.parentId
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parentId
     *
     * @param parentid the value for menu.parentId
     *
     * @mbg.generated Sat Nov 23 17:22:37 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}